name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'New Features'
    label: 'feature'
  - title: 'Breaking Change'
    label: 'breaking change'
  - title: 'Bug Fixes'
    label: 'fix'
  - title: 'Performance'
    label: 'performance'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Maintenance'
    label: 'chore'
  - title: 'Dependencies'
    label: 'dependencies'
  - title: 'Enhancement'
    label: 'enhancement'
autolabeler:
  - label: 'breaking change'
    title:
      - '/^\w+(\(.+\))?!:/'
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?:/'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?:/'
  - label: 'performance'
    title:
      - '/^perf(\(.+\))?:/'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?:/'
  - label: 'chore'
    title:
      - '/^(chore|refactor|style|test|build|ci)(\(.+\))?:/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
