# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../nbs/distributed.models.ray.lgb.ipynb.

# %% auto 0
__all__ = ['RayLGBMForecast']

# %% ../../../../nbs/distributed.models.ray.lgb.ipynb 3
import lightgbm as lgb
from lightgbm_ray import RayLGBMRegressor

# %% ../../../../nbs/distributed.models.ray.lgb.ipynb 4
class RayLGBMForecast(RayLGBMRegressor):
    @property
    def model_(self):
        return self._lgb_ray_to_local(lgb.LGBMRegressor)
