# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../nbs/distributed.models.ray.xgb.ipynb.

# %% auto 0
__all__ = ['RayXGBForecast']

# %% ../../../../nbs/distributed.models.ray.xgb.ipynb 3
import xgboost as xgb
from xgboost_ray import RayXGBRegressor

# %% ../../../../nbs/distributed.models.ray.xgb.ipynb 4
class RayXGBForecast(RayXGBRegressor):
    @property
    def model_(self):
        model_str = self.get_booster().save_raw("ubj")
        local_model = xgb.XGBRegressor()
        local_model.load_model(model_str)
        return local_model
