# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../nbs/distributed.models.dask.xgb.ipynb.

# %% auto 0
__all__ = ['DaskXGBForecast']

# %% ../../../../nbs/distributed.models.dask.xgb.ipynb 3
import xgboost as xgb

# %% ../../../../nbs/distributed.models.dask.xgb.ipynb 4
class DaskXGBForecast(xgb.dask.DaskXGBRegressor):
    @property
    def model_(self):
        model_str = self.get_booster().save_raw("ubj")
        local_model = xgb.XGBRegressor()
        local_model.load_model(model_str)
        return local_model
