# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/distributed.models.xgb.ipynb.

# %% auto 0
__all__ = ['XGBForecast']

# %% ../../../nbs/distributed.models.xgb.ipynb 3
import xgboost as xgb

# %% ../../../nbs/distributed.models.xgb.ipynb 4
class XGBForecast(xgb.dask.DaskXGBRegressor):
    @property
    def model_(self):
        model_str = self.get_booster().save_raw("ubj")
        local = xgb.XGBRegressor()
        local.load_model(model_str)
        return local
