# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/distributed.models.xgb.ipynb.

# %% auto 0
__all__ = ['XGBForecast']

# %% ../../../nbs/distributed.models.xgb.ipynb 3
import xgboost as xgb

# %% ../../../nbs/distributed.models.xgb.ipynb 4
class XGBForecast(xgb.dask.DaskXGBRegressor):
    @property
    def model_(self):
        local = xgb.XGBRegressor(**self.get_params())
        local._Booster = self._Booster
        return local
