#!/usr/bin/env python3
import re
import json
from pathlib import Path
from nbdev.clean import process_write

IP_REGEX = re.compile(r'[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
HOURS_REGEX = re.compile(r'\d{2}:\d{2}:\d{2}')

def cell_contains_ips(cell):
    if 'outputs' not in cell:
        return False
    for output in cell['outputs']:
        if 'text' not in output:
            return False
        for line in output['text']:
            if IP_REGEX.search(line) or HOURS_REGEX.search(line) or '[LightGBM]' in line:
                return True
    return False


def clean_nb(nb):
    for cell in nb['cells']:
        if cell_contains_ips(cell):
            cell['outputs'] = []


if __name__ == '__main__':
    repo_root = Path(__file__).parents[1]
    for nb in (repo_root / 'nbs').rglob('*distributed*.ipynb'):
        process_write(warn_msg='Failed to clean_nb', proc_nb=clean_nb, f_in=nb)
