# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Frame": "api.ipynb",
         "validate_data_format": "api.ipynb",
         "read_data": "api.ipynb",
         "fcst_from_config": "api.ipynb",
         "perform_backtest": "api.ipynb",
         "parse_config": "api.ipynb",
         "setup_client": "api.ipynb",
         "run_forecast": "api.ipynb",
         "date_features_dtypes": "core.ipynb",
         "GroupedArray": "core.ipynb",
         "TimeSeries": "core.ipynb",
         "TimeSeries.compute_transforms": "core.ipynb",
         "TimeSeries.update_y": "core.ipynb",
         "TimeSeries.update_features": "core.ipynb",
         "TimeSeries.get_predictions": "core.ipynb",
         "preprocessing_flow": "core.ipynb",
         "predictions_flow": "core.ipynb",
         "DataFreq": "data_model.ipynb",
         "DataFormat": "data_model.ipynb",
         "Data": "data_model.ipynb",
         "Backtest": "data_model.ipynb",
         "Features": "data_model.ipynb",
         "Forecast": "forecast.ipynb",
         "ModelConfig": "data_model.ipynb",
         "Local": "data_model.ipynb",
         "Cluster": "data_model.ipynb",
         "DistributedModelName": "data_model.ipynb",
         "DistributedModelConfig": "data_model.ipynb",
         "Distributed": "data_model.ipynb",
         "Config": "data_model.ipynb",
         "DateFeatures": "data_model.ipynb",
         "Transforms": "data_model.ipynb",
         "distributed_preprocess": "distributed.core.ipynb",
         "DistributedForecast": "distributed.forecast.ipynb",
         "BaseDistributedModel": "distributed.models.ipynb",
         "LGBMForecast": "distributed.models.ipynb",
         "XGBForecast": "distributed.models.ipynb",
         "generate_daily_series": "utils.ipynb",
         "get_last_n_mask": "utils.ipynb"}

modules = ["api.py",
           "core.py",
           "data_model.py",
           "distributed/core.py",
           "distributed/forecast.py",
           "distributed/models.py",
           "forecast.py",
           "utils.py"]

doc_url = "https://Nixtla.github.io/mlforecast/"

git_url = "https://github.com/Nixtla/mlforecast/tree/main/"

def custom_doc_links(name): return None
