# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"date_features_dtypes": "core.ipynb",
         "GroupedArray": "core.ipynb",
         "TimeSeries": "core.ipynb",
         "TimeSeries.compute_transforms": "core.ipynb",
         "TimeSeries.update_y": "core.ipynb",
         "TimeSeries.update_features": "core.ipynb",
         "TimeSeries.get_predictions": "core.ipynb",
         "preprocessing_flow": "core.ipynb",
         "generate_daily_series": "utils.ipynb"}

modules = ["core.py",
           "utils.py"]

doc_url = "https://Nixtla.github.io/mlforecast/"

git_url = "https://github.com/Nixtla/mlforecast/tree/main/"

def custom_doc_links(name): return None
