# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/compat.ipynb.

# %% auto 0
__all__ = ['Frame']

# %% ../nbs/compat.ipynb 1
from typing import Union

import pandas as pd

try:
    import dask.dataframe as dd
    from dask.dataframe import DataFrame as dd_Frame
    from dask.distributed import Client, LocalCluster

    from mlforecast.distributed.forecast import DistributedForecast
except ImportError:

    class dd:  # type: ignore
        pass

    dd_Frame = type(None)  # type: ignore

    class Client:  # type: ignore
        pass

    class LocalCluster:  # type: ignore
        pass

    class DistributedForecast:  # type: ignore
        pass

# %% ../nbs/compat.ipynb 2
Frame = Union[pd.DataFrame, dd_Frame]
