# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/compat.ipynb (unless otherwise specified).

__all__ = ['Frame']

# Cell
from typing import Union

import pandas as pd

try:
    import dask.dataframe as dd
    from dask.dataframe import DataFrame as dd_Frame
    from dask.distributed import Client, LocalCluster

    from .distributed.forecast import DistributedForecast
except ImportError:

    class dd:  # type: ignore
        pass

    dd_Frame = type(None)

    class Client:  # type: ignore
        pass

    class LocalCluster:  # type: ignore
        pass

    class DistributedForecast:  # type: ignore
        pass


try:
    from s3path import S3Path
except ImportError:

    class S3Path:  # type: ignore
        pass


# Cell
Frame = Union[pd.DataFrame, dd_Frame]
